[tool.tartufo]
repo-path = "."

exclude-path-patterns = [
    { path-pattern='.*/go\.(sum)', reason='Go dependency files' },
    { path-pattern='tartufo\.toml', reason='Tartufo file' },
]

exclude-entropy-patterns = [
    { path-pattern='.github/workflows/.*\.ya?ml', pattern='uses: .*@[a-f\d]{40}', reason='GitHub Action uses Hash' },
    { path-pattern='docker/.*_test\.go', pattern='sha256:[a-f\d]{64}', reason='Test docker Image SHA, not sensitive' },
    { path-pattern='docker/normalize\.go', pattern='exceptions/[a-f\d]{40}', reason='Exception ID MD5 Hash, not sensitive' },
    { path-pattern='README\.md', pattern='https://cloud.int.godaddy.com/compute/vms.*', reason='Openstack URL, not sensitive' },
    { path-pattern='test/integration_test\.sh', pattern='AWS_DEFAULT_REGION=[a-z-\d]*', match-type='match', scope='word', reason='AWS Region' },
    { path-pattern='test/.*_test\.go', pattern='Test[a-zA-Z\d_]*', match-type='match', scope='word', reason='Test Names' },
    { path-pattern='\.pre-commit-config\.yaml', pattern='rev: [a-f\d]{40}', reason='Release MD5 hash, not sensitive' },
]
