name: Repository Build Workflow

on:
  pull_request:
    branches:
      - 'main'

jobs:
  tartufo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Checkout GoDaddy Actions repo. # Checkout shared actions repository gd-actions
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: gdcorp-actions/tartufo
          token: ${{ secrets.REPO_CLONE_TOKEN }} # PAT with read access to gdcorp-cp/gd-actions
          ref: v2.1.0 # https://godaddy.slack.com/archives/C011GSS1CES/p1617653572031100
          path: tartufo # Relative to github working directory
          persist-credentials: false
      - name: Run Tartufo Scan.
        uses: ./tartufo # Relative reference to action in gd-actions repository
        with:
          github_token: ${{ secrets.REPO_CLONE_TOKEN }}

  go-build:
    needs: tartufo-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Set up Go
        uses: actions/setup-go@3b4dc6cbed1779f759b9c638cb83696acea809d1
        with:
          go-version: '1.15.6'
      - name: Run Tests
        run: |
          cd docker
          go get
          go test ./... -coverprofile coverage.out -args some test args here && go tool cover -func=coverage.out
      - name: Run Build
        run: |
          cd docker
          go build
