name: Repository Build Workflow

on:
  pull_request:
    branches:
      - "main"

jobs:
  tartufo-job:
    runs-on: [self-hosted, product-security, non-pci, utility]
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        name: Checkout the repo
      - uses: godaddy/tartufo-action@37f3389ebfb544c729e6427e6ff545dc00d8a0b2 # v4.0.0
        name: Run Tartufo

  go-build:
    needs: tartufo-job
    runs-on: [self-hosted, product-security, non-pci, utility]
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Set up Go
        uses: actions/setup-go@3b4dc6cbed1779f759b9c638cb83696acea809d1
        with:
          go-version: "1.21"
      - name: Run Tests
        run: |
          cd docker
          go get
          go test ./... -coverprofile coverage.out && go tool cover -func=coverage.out
      - name: Run Build
        run: |
          cd docker
          go build
