on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "sceptre/**"
      - ".github/workflows/sceptre.yml"

name: scan bad container image with vulnerabilities
env:
  CONTAINER_IMAGE_TWISTCLI: 123456789.dkr.ecr.us-east-1.amazonaws.com/scanner:latest
  CONTAINER_BAD_IMAGE_TEST: 123456789.dkr.ecr.us-east-1.amazonaws.com/bad:latest

jobs:
  build-and-scan:
    name: Build and Scan for Vulnerabilities
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Configure AWS credentials using Cloud Key Based Service Accounts
      uses: aws-actions/configure-aws-credentials@1ed6eed14f0f832cad5830fb357d937c2f20ec67
      with:
        aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_TOKEN_VALUE }}
        role-to-assume: ${{ secrets.DEV_PRIVATE_AWS_DEPLOY_ROLE }}
        role-duration-seconds: 3600
        aws-region: us-west-2

    - name: Log into golden image ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com

    - name: Build and tag the image twistcli
      run: docker build -t ${{env.CONTAINER_IMAGE_TWISTCLI}} -t ${{github.sha}} ./docker

    - name: Build and tag vulnerable image for test scan
      run: cd ./test && docker build -t ${{env.CONTAINER_BAD_IMAGE_TEST}} . -f bad.go.Dockerfile 

    - name: Scan bad image without posting github status
      continue-on-error: true
      run: |
        PR_SHA=${{github.event.pull_request.head.sha}}
        docker run \
        --rm \
        --group-add $(stat -c '%g' /var/run/docker.sock) \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        -e AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY \
        -e AWS_SESSION_TOKEN \
        -e AWS_DEFAULT_REGION \
        -e TARGET_URL=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} \
        -e GITHUB_URL=https://github.com/ \
        -e PAT=${{github.token}} \
        -e GITHUB_REPO=${{github.repository}} \
        -e COMMIT_SHA=${PR_SHA:-${{github.sha}}} \
        -e CONTAINER=${{env.CONTAINER_BAD_IMAGE_TEST}} \
        ${{env.CONTAINER_IMAGE_TWISTCLI}}

    - name: Scan bad image with JSON output
      continue-on-error: true
      run: |
        PR_SHA=${{github.event.pull_request.head.sha}}
        docker run \
        --rm \
        --group-add $(stat -c '%g' /var/run/docker.sock) \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        -e AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY \
        -e AWS_SESSION_TOKEN \
        -e AWS_DEFAULT_REGION \
        -e TARGET_URL=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} \
        -e GITHUB_URL=https://github.com/ \
        -e PAT=${{github.token}} \
        -e GITHUB_REPO=${{github.repository}} \
        -e COMMIT_SHA=${PR_SHA:-${{github.sha}}} \
        -e CONTAINER=${{env.CONTAINER_BAD_IMAGE_TEST}} \
        -e FORMAT=json \
        ${{env.CONTAINER_IMAGE_TWISTCLI}}
