on: [push, pull_request]

name: scan container images
env:   
  CONTAINER_IMAGE_TWISTCLI: containerscan
  CONTAINER_IMAGE_TEST: 226955763576.dkr.ecr.us-east-1.amazonaws.com/testcontainer:latest

jobs:
  build-and-scan:
    name: Build and Scan for Vulnerabilities
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Configure AWS credentials using Cloud Key Based Service Accounts
      uses: aws-actions/configure-aws-credentials@1ed6eed14f0f832cad5830fb357d937c2f20ec67
      with:
        aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_TOKEN_VALUE }}
        role-to-assume: ${{ secrets.DEV_PRIVATE_AWS_DEPLOY_ROLE }}
        role-duration-seconds: 3600
        aws-region: us-west-2

    - name: Check AWS Role
      run: aws sts get-caller-identity

    - name: Log into golden image ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com


    - name: Build and tag the image twistcli
      run: docker build -t ${{env.CONTAINER_IMAGE_TWISTCLI}} -t ${{github.sha}} ./docker
    
    - name: Build and tag the image for test scan
      run: docker build -t ${{env.CONTAINER_IMAGE_TEST}} -t ${{github.sha}} ./test
        
    - name: Scan the image               
      run: |
        docker run --rm --group-add $(stat -f '%g' /var/run/docker.sock) -v /var/run/docker.sock:/var/run/docker.sock:ro  -e AWS_ACCESS_KEY_ID  -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e AWS_DEFAULT_REGION -e CONTAINER=${{env.CONTAINER_IMAGE_TEST}} ${{env.CONTAINER_IMAGE_TWISTCLI}}      

  # - name: Push Image to ECR
  # run: docker push $(LOGAGG_REPO)/$(LOGAGG_IMAGE) --all-tags