on: [push, pull_request]

name: scan container images
env:
  TL_USER: ${{ secrets.TL_USER }}
  TL_PASS: ${{ secrets.TL_PASS }}
    
  CONTAINER_IMAGE: badcontainer
  CONTAINER_IMAGE_TWISTCLI: containerscan

jobs:
  build-and-scan:
    name: Build and Scan for Vulnerabilities
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Build and tag the image
      # run: docker build -t $CONTAINER_IMAGE .

    - name: Build and tag the image twistcli
      run: docker build -t $CONTAINER_IMAGE_TWISTCLI ./docker
    
    - name: Build bad container
      run: docker build -t $CONTAINER_IMAGE ./test

    - name: Scan the image
      env:
        TL_USER: ${{ secrets.PRISMA_ACCESSKEY }}
        TL_PASS: ${{ secrets.PRISMA_SECRET_ID }}
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro  -e AK=${TL_USER} -e SI=${TL_PASS} -e CONTAINER=${CONTAINER_IMAGE} $CONTAINER_IMAGE_TWISTCLI
       
       