name: Update AWS Prisma Secrets Infra

on:
  pull_request:
    branches: [main]
    paths:
      - "sceptre/**"
      - ".github/workflows/sceptre.yml"

  push:
    branches: [main]
    paths:
      - "sceptre/**"
      - ".github/workflows/sceptre.yml"

jobs:
  tartufo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Checkout GoDaddy Actions repo. # Checkout shared actions repository gd-actions
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: gdcorp-actions/tartufo
          token: ${{ secrets.REPO_CLONE_TOKEN }} # PAT with read access to gdcorp-cp/gd-actions
          ref: v2.1.0 #  https://godaddy.slack.com/archives/C011GSS1CES/p1617653572031100
          path: tartufo # Relative to github working directory
          persist-credentials: false
      - name: Run Tartufo Scan.
        uses: ./tartufo # Relative reference to action in gd-actions repository
        with:
          github_token: ${{ secrets.REPO_CLONE_TOKEN }}

  checkout-code:
    needs: tartufo-job
    runs-on: self-hosted
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #  Checkout this repository.

  deploy-s3-prisma-infrastructure:
    runs-on: self-hosted
    needs: checkout-code
    steps:
      - name: Configure AWS credentials using Cloud Key Based Service Accounts
        uses: aws-actions/configure-aws-credentials@1417e62aeacec5e7fbe447bb7712d50847507342
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.PROD_AWS_DEPLOY_ROLE }}
          role-duration-seconds: 3600
          aws-region: us-east-1

      - name: Deploy/Update ECR sceptre deployment
        working-directory: ./sceptre
        run: |
          sceptre launch -y s3-bucket-prisma.yaml

      - name: Update with new Prisma Secret
        run: |
          jq -n '{"prismaAccessKeyId": "${{ secrets.PRISMA_ACCESS_KEY_ID }}", "prismaSecretKey": "${{ secrets.PRISMA_SECRET_KEY }}"}' > prisma-secret.json
          aws s3api put-object --key prisma-secret.json --body prisma-secret.json --bucket gd-security-prod-prisma-storage
          rm -irf prisma-secret.json
